services:
  - type: web
    name: exifvault
    env: node
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y libimage-exiftool-perl && \
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
